# log configuration
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO

# server configuration
server:
  port: 9080
  servlet:
    context-path: /api

# application properties
application:
  name: Jenkins Pipeline Demo Project
  description: This is a Spring Boot application

# Spring environment configuration
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

management:
  server:
    port: 9001
    base-path: monitor
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - beans
        exclude:
          - env

# Disabling the swagger-ui
springdoc:
  swagger-ui:
    enabled: true

